[env:freenove_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    ArduinoOTA
    gin66/FastAccelStepper
    thomasfredericks/Bounce2@^2.71
    ESP32Async/ESPAsyncWebServer@^3.6.0
    ESP32Async/AsyncTCP@^3.3.2
    bblanchon/ArduinoJson@^7.4.2

upload_protocol = espota
upload_port = 192.168.1.228
; upload_protocol = esptool
